version: '3.7'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn engineer_django.wsgi:application --bind 0.0.0.0:80 --reload
    volumes:
      - static:/home/app/web/engineer_django/static
    restart: unless-stopped
    expose:
      - 80
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/engineer_django/static
      - media:/home/app/web/engineer_django/media
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
