version: "3.7"
   
services:
  web:
    build: ./app
    command: python engineer_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/opt/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=engineer_django
      - POSTGRES_PASSWORD=engineer_django
      - POSTGRES_DB=engineer_django_dev

volumes:
  postgres_data:
