version: '3.7'
services:
  web_prod:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn engineer_django.wsgi:application --bind 0.0.0.0:80
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 80
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
  db_prod:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/engineer_django/static
      - media_volume:/home/app/web/engineer_django/media
    ports:
      - 80:80
    depends_on:
      - web_prod

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
